name: WHITEOUT
favicon: null
layout_spectrum: 0.8695378131233156
typography_spectrum: 0.769085741834715
title: WHITEOUT MANAGEMENT
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a6aeb0'
    - '#0d1011'
    - '#ffffff'
    - '#7f7f7f'
    - '#474747'
  brandStrength: 0.6341806496493518
  lightness: 0.30628889286890626
  saturation: 0.30216418066993356
  rhythmicContrast: 0.9306410739663988
purpose: []
