name: WHITEOUT
favicon: null
layout_spectrum: 0.08188
typography_spectrum: 0.6021277
title: WHITEOUT MANAGEMENT
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#040304'
    - '#fffeff'
    - '#5e5b5e'
    - '#8d8b8d'
    - '#c4c2c4'
  brandStrength: 0.1875
  lightness: 0.625
  saturation: 0.5
  rhythmicContrast: 0.9306410739663988
purpose: []
